### ISSUE TITLE
OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by jordoh** [tdrussell/diffusion-pipe#12]
I'm able to train hunyuan successfully with images, but have been getting an error when training with videos (50 720x540 .mov videos, ~80 frames each). The exception happens after 2-13 steps, each of the three times I've tried it has been at a seemingly random point.

Exception:
```
[2024-12-16 05:50:23,709] [INFO] [logging.py:128:log_dist] [Rank 0] step=2, skipped=0, lr=[2.9800000000000007e-06], mom=[0.0]
steps: 2 loss: 0.0620 iter time (s): 104.915 samples/sec: 0.038
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
    self._run()
  File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
    self._record_writer.write(data)
  File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 775, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 167, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 171, in _write
    with io.open(filename, mode, encoding=encoding) as f:
OSError: [Errno 5] Input/output error
[2024-12-16 05:54:49,840] [INFO] [logging.py:128:log_dist] [Rank 0] step=3, skipped=0, lr=[3.970000000000001e-06], mom=[0.0]
steps: 3 loss: 0.0971 iter time (s): 266.107 samples/sec: 0.015
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 468, in <module>
[rank0]:     tb_writer.add_scalar(f'train/loss', loss, step)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 381, in add_scalar
[rank0]:     self._get_file_writer().add_summary(summary, global_step, walltime)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 115, in add_summary
[rank0]:     self.add_event(event, global_step, walltime)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/torch/utils/tensorboard/writer.py", line 99, in add_event
[rank0]:     self.event_writer.add_event(event)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 117, in add_event
[rank0]:     self._async_writer.write(event.SerializeToString())
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 171, in write
[rank0]:     self._check_worker_status()
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 212, in _check_worker_status
[rank0]:     raise exception
[rank0]:   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
[rank0]:     self.run()
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 244, in run
[rank0]:     self._run()
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/event_file_writer.py", line 275, in _run
[rank0]:     self._record_writer.write(data)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/summary/writer/record_writer.py", line 40, in write
[rank0]:     self._writer.write(header + header_crc + data + footer_crc)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 775, in write
[rank0]:     self.fs.append(self.filename, file_content, self.binary_mode)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 167, in append
[rank0]:     self._write(filename, file_content, "ab" if binary_mode else "a")
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 171, in _write
[rank0]:     with io.open(filename, mode, encoding=encoding) as f:
[rank0]: OSError: [Errno 5] Input/output error
[2024-12-16 05:55:04,016] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 23083
[2024-12-16 05:55:04,016] [ERROR] [launch.py:325:sigkill_handler] ['/workspace/diffusion-pipe/venv/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml'] exits with return code = 1
```

**Comment by jordoh** [comment]
Update: setting `gradient_accumulation_steps = 1` (exception was with the default example config's `gradient_accumulation_steps = 4`) has let me get past 500 steps (still running), so this appears to be an issue related to batching. I've noted that I'm unable to change the batch size options directly: only changing `gradient_accumulation_steps` has affected the batch size used during training. 

My training videos are of different lengths, and I haven't taken time to configure the frame-count buckets to bucket them (I think they are almost all over the longest bucket in the default config), so perhaps this happens when differing length videos that are bucketed together get processed in a batch together.

**Comment by tdrussell** [comment]
>so perhaps this happens when differing length videos that are bucketed together get processed in a batch together.

I don't think this can happen. The entire global batch, which is split across GPUs, then split into micro batches for gradient accumulation through the pipelined layers, should all be the same size bucket. For videos, the video length will be greater than or equal to the frame length of the size bucket, but then the code has a method to extract clips from the video of exactly the right length. Of course it's possible I messed something up. I can try to take a look when I have time. I've done very little testing of video training.

Are you using multiple GPUs and setting pipeline_stages>1? Also the error you posted is an I/O error when writing to Tensorboard. It's odd that gradient accumulation steps would have anything to do with that.

**Comment by jordoh** [comment]
Single GPU and `pipeline_stages = 1` - I'm using the example hunyuan config, prior to changing the gradient accumulation steps, I had only changed the paths and LR in the example config (let me know if the config would be useful and I can post it in full).

I'm not at all sure the gradient accumulation steps are the issue - I've been unable to lower the batch size without lowering gradient accumulation steps, so it seems more likely to me to be an issue with the batch size. It certainly seems reasonable to close this issue as there are no other reports and gradient accumulation 1 (therefore batch size = 1) is working, but I wanted to raise it as this was consistently happening (at a random-seeming point) prior to adjusting that. I looked through tensorboard's issues, as I did think it seemed more like a parallelism issue there, but wasn't able to find anything pertinent.

**Comment by tdrussell** [comment]
What machine are you running this on? Rented instance? Colab? I googled and saw that something like your original error can happen on Colab due to some quota issue.

**Comment by jordoh** [comment]
> What machine are you running this on? Rented instance? Colab? I googled and saw that something like your original error can happen on Colab due to some quota issue.

Runpod instance. Doesn't seem like it's due to the machine, as I've been running successfully on the same instance since changing `gradient_accumulation_steps`, but I couldn't rule that out as it was at seemingly random times.

**Comment by jordoh** [comment]
Closing as I've been able to train successfully since opening this issue.
