### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by Cubey42** [tdrussell/diffusion-pipe#2]
I'm not even sure what the error is, but it fails
```
[2024-12-11 17:41:18,618] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-11 17:41:20,616] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-12-11 17:41:20,616] [INFO] [runner.py:607:main] cmd = /home/cubeyai/anaconda/envs/diffusion-pipe/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed --config examples/hunyuan_video.toml
[2024-12-11 17:41:21,477] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-11 17:41:22,750] [INFO] [launch.py:139:main] 0 NCCL_IB_DISABLE=1
[2024-12-11 17:41:22,751] [INFO] [launch.py:139:main] 0 NCCL_P2P_DISABLE=1
[2024-12-11 17:41:22,751] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2024-12-11 17:41:22,751] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2024-12-11 17:41:22,751] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2024-12-11 17:41:22,751] [INFO] [launch.py:164:main] dist_world_size=1
[2024-12-11 17:41:22,751] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2024-12-11 17:41:22,751] [INFO] [launch.py:256:main] process 562154 spawned with command: ['/home/cubeyai/anaconda/envs/diffusion-pipe/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml']
[2024-12-11 17:41:23,623] [INFO] [real_accelerator.py:219:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-11 17:41:25,527] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-12-11 17:41:25,527] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
The config attributes {'tile_sample_min_size': 256} were passed to AutoencoderKLCausal3D, but are not expected and will be ignored. Please verify your config.json configuration file.
2024-12-11 17:41:26.650 | INFO     | hyvideo.text_encoder:load_text_encoder:28 - Loading text encoder model (llm) from: ./models/HY/llava-llama-3-8b-text-encoder-tokenizer
Loading checkpoint shards: 100%|██████████████████████████████████████████████| 4/4 [00:08<00:00,  2.03s/it]
2024-12-11 17:41:38.619 | INFO     | hyvideo.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.bfloat16
2024-12-11 17:41:38.622 | INFO     | hyvideo.text_encoder:load_tokenizer:64 - Loading tokenizer (llm) from: ./models/HY/llava-llama-3-8b-text-encoder-tokenizer
2024-12-11 17:41:39.068 | INFO     | hyvideo.text_encoder:load_text_encoder:28 - Loading text encoder model (clipL) from: ./models/HY/clip-vit-large-patch14
2024-12-11 17:41:39.378 | INFO     | hyvideo.text_encoder:load_text_encoder:50 - Text encoder to dtype: torch.bfloat16
2024-12-11 17:41:39.379 | INFO     | hyvideo.text_encoder:load_tokenizer:64 - Loading tokenizer (clipL) from: ./models/HY/clip-vit-large-patch14
using video_clip_mode=single_middle
caching latents: Hakos_Baelz
caching latents: Hakos_Baelz
trainable params: 161,218,560 || all params: 12,982,231,104 || trainable%: 1.2418
SEED_LAYERS=False BASE_SEED=1234 SEED_FN=None
Using topology: {ProcessCoord(pipe=0, data=0): 0}
[2024-12-11 17:41:42,605] [INFO] [module.py:396:_partition_layers] Partitioning pipeline stages with method parameters
stage=0 layers=63
     0: InitialLayer
     1: DoubleBlock
     2: DoubleBlock
     3: DoubleBlock
     4: DoubleBlock
     5: DoubleBlock
     6: DoubleBlock
     7: DoubleBlock
     8: DoubleBlock
     9: DoubleBlock
    10: DoubleBlock
    11: DoubleBlock
    12: DoubleBlock
    13: DoubleBlock
    14: DoubleBlock
    15: DoubleBlock
    16: DoubleBlock
    17: DoubleBlock
    18: DoubleBlock
    19: DoubleBlock
    20: DoubleBlock
    21: concatenate_hidden_states
    22: SingleBlock
    23: SingleBlock
    24: SingleBlock
    25: SingleBlock
    26: SingleBlock
    27: SingleBlock
    28: SingleBlock
    29: SingleBlock
    30: SingleBlock
    31: SingleBlock
    32: SingleBlock
    33: SingleBlock
    34: SingleBlock
    35: SingleBlock
    36: SingleBlock
    37: SingleBlock
    38: SingleBlock
    39: SingleBlock
    40: SingleBlock
    41: SingleBlock
    42: SingleBlock
    43: SingleBlock
    44: SingleBlock
    45: SingleBlock
    46: SingleBlock
    47: SingleBlock
    48: SingleBlock
    49: SingleBlock
    50: SingleBlock
    51: SingleBlock
    52: SingleBlock
    53: SingleBlock
    54: SingleBlock
    55: SingleBlock
    56: SingleBlock
    57: SingleBlock
    58: SingleBlock
    59: SingleBlock
    60: SingleBlock
    61: SingleBlock
    62: OutputLayer
[2024-12-11 17:41:48,020] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed info: version=0.16.1, git-hash=unknown, git-branch=unknown
[2024-12-11 17:41:48,021] [INFO] [config.py:733:__init__] Config mesh_device None world_size = 1
[2024-12-11 17:41:48,089] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2024-12-11 17:41:48,095] [INFO] [logging.py:128:log_dist] [Rank 0] Using client callable to create basic optimizer
[2024-12-11 17:41:48,095] [INFO] [logging.py:128:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2024-12-11 17:41:48,130] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed Basic Optimizer = AdamW
[2024-12-11 17:41:48,130] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed Final Optimizer = AdamW
[2024-12-11 17:41:48,130] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed using configured LR scheduler = None
[2024-12-11 17:41:48,130] [INFO] [logging.py:128:log_dist] [Rank 0] DeepSpeed LR Scheduler = None
[2024-12-11 17:41:48,130] [INFO] [logging.py:128:log_dist] [Rank 0] step=0, skipped=0, lr=[2e-05], mom=[0.0]
[2024-12-11 17:41:48,135] [INFO] [config.py:999:print] DeepSpeedEngine configuration:
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   activation_checkpointing_config  {
    "partition_activations": false,
    "contiguous_memory_optimization": false,
    "cpu_checkpointing": false,
    "number_checkpoints": null,
    "synchronize_checkpoint_boundary": false,
    "profile": false
}
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   aio_config ................... {'block_size': 1048576, 'queue_depth': 8, 'thread_count': 1, 'single_submit': False, 'overlap_events': True, 'use_gds': False}
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   amp_enabled .................. False
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   amp_params ................... False
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   autotuning_config ............ {
    "enabled": false,
    "start_step": null,
    "end_step": null,
    "metric_path": null,
    "arg_mappings": null,
    "metric": "throughput",
    "model_info": null,
    "results_dir": "autotuning_results",
    "exps_dir": "autotuning_exps",
    "overwrite": true,
    "fast": true,
    "start_profile_step": 3,
    "end_profile_step": 5,
    "tuner_type": "gridsearch",
    "tuner_early_stopping": 5,
    "tuner_num_trials": 50,
    "model_info_path": null,
    "mp_size": 1,
    "max_train_batch_size": null,
    "min_train_batch_size": 1,
    "max_train_micro_batch_size_per_gpu": 1.024000e+03,
    "min_train_micro_batch_size_per_gpu": 1,
    "num_tuning_micro_batch_sizes": 3
}
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   bfloat16_enabled ............. False
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   bfloat16_immediate_grad_update  False
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   checkpoint_parallel_write_pipeline  False
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   checkpoint_tag_validation_enabled  True
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   checkpoint_tag_validation_fail  False
[2024-12-11 17:41:48,135] [INFO] [config.py:1003:print]   comms_config ................. <deepspeed.comm.config.DeepSpeedCommsConfig object at 0x7fc13884dcd0>
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   communication_data_type ...... None
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   compression_config ........... {'weight_quantization': {'shared_parameters': {'enabled': False, 'quantizer_kernel': False, 'schedule_offset': 0, 'quantize_groups': 1, 'quantize_verbose': False, 'quantization_type': 'symmetric', 'quantize_weight_in_forward': False, 'rounding': 'nearest', 'fp16_mixed_quantize': False, 'quantize_change_ratio': 0.001}, 'different_groups': {}}, 'activation_quantization': {'shared_parameters': {'enabled': False, 'quantization_type': 'symmetric', 'range_calibration': 'dynamic', 'schedule_offset': 1000}, 'different_groups': {}}, 'sparse_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'row_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'head_pruning': {'shared_parameters': {'enabled': False, 'method': 'topk', 'schedule_offset': 1000}, 'different_groups': {}}, 'channel_pruning': {'shared_parameters': {'enabled': False, 'method': 'l1', 'schedule_offset': 1000}, 'different_groups': {}}, 'layer_reduction': {'enabled': False}}
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   curriculum_enabled_legacy .... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   curriculum_params_legacy ..... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   data_efficiency_config ....... {'enabled': False, 'seed': 1234, 'data_sampling': {'enabled': False, 'num_epochs': 1000, 'num_workers': 0, 'curriculum_learning': {'enabled': False}}, 'data_routing': {'enabled': False, 'random_ltd': {'enabled': False, 'layer_token_lr_schedule': {'enabled': False}}}}
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   data_efficiency_enabled ...... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   dataloader_drop_last ......... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   disable_allgather ............ False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   dump_state ................... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   dynamic_loss_scale_args ...... None
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_enabled ........... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_gas_boundary_resolution  1
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_layer_name ........ bert.encoder.layer
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_layer_num ......... 0
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_max_iter .......... 100
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_stability ......... 1e-06
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_tol ............... 0.01
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   eigenvalue_verbose ........... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   elasticity_enabled ........... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   flops_profiler_config ........ {
    "enabled": false,
    "recompute_fwd_factor": 0.0,
    "profile_step": 1,
    "module_depth": -1,
    "top_modules": 1,
    "detailed": true,
    "output_file": null
}
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   fp16_auto_cast ............... None
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   fp16_enabled ................. False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   fp16_master_weights_and_gradients  False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   global_rank .................. 0
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   grad_accum_dtype ............. None
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   gradient_accumulation_steps .. 4
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   gradient_clipping ............ 1.0
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   gradient_predivide_factor .... 1.0
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   graph_harvesting ............. False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   hybrid_engine ................ enabled=False max_out_tokens=512 inference_tp_size=1 release_inference_cache=False pin_parameters=True tp_gather_partition_size=8
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   initial_dynamic_scale ........ 65536
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   load_universal_checkpoint .... False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   loss_scale ................... 0
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   memory_breakdown ............. False
[2024-12-11 17:41:48,136] [INFO] [config.py:1003:print]   mics_hierarchial_params_gather  False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   mics_shard_size .............. -1
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   monitor_config ............... tensorboard=TensorBoardConfig(enabled=False, output_path='', job_name='DeepSpeedJobName') comet=CometConfig(enabled=False, samples_log_interval=100, project=None, workspace=None, api_key=None, experiment_name=None, experiment_key=None, online=None, mode=None) wandb=WandbConfig(enabled=False, group=None, team=None, project='deepspeed') csv_monitor=CSVConfig(enabled=False, output_path='', job_name='DeepSpeedJobName')
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   nebula_config ................ {
    "enabled": false,
    "persistent_storage_path": null,
    "persistent_time_interval": 100,
    "num_of_version_in_retention": 2,
    "enable_nebula_load": true,
    "load_path": null
}
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   optimizer_legacy_fusion ...... False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   optimizer_name ............... None
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   optimizer_params ............. None
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   pipeline ..................... {'stages': 'auto', 'partition': 'best', 'seed_layers': False, 'activation_checkpoint_interval': 0, 'pipe_partitioned': True, 'grad_partitioned': True}
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   pld_enabled .................. False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   pld_params ................... False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   prescale_gradients ........... False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   scheduler_name ............... None
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   scheduler_params ............. None
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   seq_parallel_communication_data_type  torch.float32
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   sparse_attention ............. None
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   sparse_gradients_enabled ..... False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   steps_per_print .............. 1
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   timers_config ................ enabled=True synchronized=True
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   train_batch_size ............. 4
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   train_micro_batch_size_per_gpu  1
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   use_data_before_expert_parallel_  False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   use_node_local_storage ....... False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   wall_clock_breakdown ......... False
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   weight_quantization_config ... None
[2024-12-11 17:41:48,137] [INFO] [config.py:1003:print]   world_size ................... 1
[2024-12-11 17:41:48,138] [INFO] [config.py:1003:print]   zero_allow_untested_optimizer  False
[2024-12-11 17:41:48,138] [INFO] [config.py:1003:print]   zero_config .................. stage=0 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=500000000 use_multi_rank_bucket_allreduce=True allgather_partitions=True allgather_bucket_size=500000000 overlap_comm=False load_from_fp32_weights=True elastic_checkpoint=False offload_param=None offload_optimizer=None sub_group_size=1000000000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=50000000 param_persistence_threshold=100000 model_persistence_threshold=9223372036854775807 max_live_parameters=1000000000 max_reuse_distance=1000000000 gather_16bit_weights_on_model_save=False module_granularity_threshold=0 use_all_reduce_for_fetch_params=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters=True legacy_stage1=False round_robin_gradients=False zero_hpz_partition_size=1 zero_quantized_weights=False zero_quantized_nontrainable_weights=False zero_quantized_gradients=False mics_shard_size=-1 mics_hierarchical_params_gather=False memory_efficient_linear=True pipeline_loading_checkpoint=False override_module_apply=True
[2024-12-11 17:41:48,138] [INFO] [config.py:1003:print]   zero_enabled ................. False
[2024-12-11 17:41:48,138] [INFO] [config.py:1003:print]   zero_force_ds_cpu_optimizer .. True
[2024-12-11 17:41:48,138] [INFO] [config.py:1003:print]   zero_optimization_stage ...... 0
[2024-12-11 17:41:48,138] [INFO] [config.py:989:print_user_config]   json = {
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 4,
    "gradient_clipping": 1.0,
    "steps_per_print": 1
}
[2024-12-11 17:41:48,138] [INFO] [engine.py:105:__init__] CONFIG: micro_batches=4 micro_batch_size=1
[2024-12-11 17:41:48,138] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2024-12-11 17:41:48,160] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=63 [0, 63) STAGE_PARAMS=161218560 (161.219M) TOTAL_PARAMS=161218560 (161.219M) UNIQUE_PARAMS=161218560 (161.219M)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/cubeyai/diffusion-pipe/train.py", line 462, in <module>
[rank0]:     loss = model_engine.train_batch().item()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/anaconda/envs/diffusion-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 389, in train_batch
[rank0]:     self._exec_schedule(sched)
[rank0]:   File "/home/cubeyai/anaconda/envs/diffusion-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 1422, in _exec_schedule
[rank0]:     self._exec_instr(**cmd.kwargs)
[rank0]:   File "/home/cubeyai/anaconda/envs/diffusion-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 886, in _exec_load_micro_batch
[rank0]:     batch = self._next_batch()
[rank0]:             ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/anaconda/envs/diffusion-pipe/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 701, in _next_batch
[rank0]:     batch = next(self.data_iterator)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/cubeyai/diffusion-pipe/utils/dataset.py", line 658, in __next__
[rank0]:     self.next_micro_batch = next(self.data)
[rank0]:                             ^^^^^^^^^^^^^^^
[rank0]: StopIteration
[2024-12-11 17:42:01,124] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 562154
[2024-12-11 17:42:01,170] [ERROR] [launch.py:325:sigkill_handler] ['/home/cubeyai/anaconda/envs/diffusion-pipe/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml'] exits with return code = 1
```

**Comment by tdrussell** [comment]
The clue seems to be where it logs "caching latents:" but then doesn't go on to log the size buckets it's caching under that. It's like it can't find any images or videos in the directory you pointed it to, or it is skipping those files because it can't open them, or something.

Do media files and caption .txt files exist in the directory you configured in the dataset TOML file?
Is it images, or videos?
Is this training run loaded from cache (i.e. did you previously run it and it cached everything then)? If you ever ran it against an empty directory, it might make empty cache files, which it would always reuse. You would have to delete the cache dir or use --regenerate_cache flag.

I will at least add a check to the code so it errors out with a message that it found no images.

**Comment by Cubey42** [comment]
> The clue seems to be where it logs "caching latents:" but then doesn't go on to log the size buckets it's caching under that. It's like it can't find any images or videos in the directory you pointed it to, or it is skipping those files because it can't open them, or something.
> 
> Do media files and caption .txt files exist in the directory you configured in the dataset TOML file? Is it images, or videos? Is this training run loaded from cache (i.e. did you previously run it and it cached everything then)? If you ever ran it against an empty directory, it might make empty cache files, which it would always reuse. You would have to delete the cache dir or use --regenerate_cache flag.
> 
> I will at least add a check to the code so it errors out with a message that it found no images.

sorry as I was away, I found the cause to be that I ran the file once before to test, I think I made a change to the dataset and that caused the error. side question, I have a checkpoint that is saved but I think I made the epoch way too large, is there anyway to convert the checkpoint to a safetensor?

**Comment by Cubey42** [comment]
If I try to change the num_repeats, the same issue as above occurs.

**Comment by tdrussell** [comment]
In general, changing anything (especially about the dataset and its config) and then trying to resume will cause problems. If you changed something, when in doubt use --regenerate_cache and make it a fresh training run.

> is there anyway to convert the model_states to a safetensor

Not easily. If you can code, you can try adapting this: https://github.com/tdrussell/qlora-pipe/blob/main/convert_ds_checkpoint_to_lora.py
Long ago I screwed up my first training runs with another training script and made this to convert the Deepspeed checkpoints to a lora. I highly doubt it works out of the box for this case though, but that's the general technique.

**Comment by Cubey42** [comment]
Yeah I can't really so I'll just lose the 4 hours, but thanks for the advice 👍

**Comment by Cubey42** [comment]
also, I don't think multiple paths are working, I tried one with two folders and got [rank0]: ValueError: Duplicate keys!

**Comment by tdrussell** [comment]
What does your dataset config look like? It should be something like this:

[[directory]]
path = '/path/to/something'

[[directory]]
path = '/path/to/something_else'

I am successfully training with multiple paths like this.
