### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by popovidis** [tdrussell/diffusion-pipe#21]
Hello, I am having an issue getting the training to work.

I have tried to debug this with ChatGPT and it suggested I add this to the training command to help resolve the libcudart import error but it did not sadly. "LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:$LD_LIBRARY_PATH"

Cuda, nvidia, and everything is installed just fine. What else can I try?

Here is the entire output of the terminal:

```
(venv) root@****:/workspace/diffusion-pipe# LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:$LD_LIBRARY_PATH NCCL_P2P_DISABLE="1" NCCL_IB_DISABLE="1" deepspeed --num_gpus=1 train.py --deepspeed --config examples/hunyuan_video.toml
[2024-12-20 11:06:50,460] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-20 11:07:06,574] [WARNING] [runner.py:215:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2024-12-20 11:07:06,575] [INFO] [runner.py:607:main] cmd = /workspace/diffusion-pipe/venv/bin/python3 -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --enable_each_rank_log=None train.py --deepspeed --config examples/hunyuan_video.toml
[2024-12-20 11:07:12,529] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-20 11:07:22,615] [INFO] [launch.py:139:main] 0 NCCL_IB_DISABLE=1
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NCCL_P2P_DISABLE=1
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE=libnccl-dev=2.17.1-1+cuda12.1
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_VERSION=2.17.1-1
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NCCL_VERSION=2.17.1-1
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_DEV_PACKAGE_NAME=libnccl-dev
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE=libnccl2=2.17.1-1+cuda12.1
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_NAME=libnccl2
[2024-12-20 11:07:22,616] [INFO] [launch.py:139:main] 0 NV_LIBNCCL_PACKAGE_VERSION=2.17.1-1
[2024-12-20 11:07:22,616] [INFO] [launch.py:146:main] WORLD INFO DICT: {'localhost': [0]}
[2024-12-20 11:07:22,616] [INFO] [launch.py:152:main] nnodes=1, num_local_procs=1, node_rank=0
[2024-12-20 11:07:22,617] [INFO] [launch.py:163:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2024-12-20 11:07:22,617] [INFO] [launch.py:164:main] dist_world_size=1
[2024-12-20 11:07:22,617] [INFO] [launch.py:168:main] Setting CUDA_VISIBLE_DEVICES=0
[2024-12-20 11:07:22,619] [INFO] [launch.py:256:main] process 7500 spawned with command: ['/workspace/diffusion-pipe/venv/bin/python3', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml']
[2024-12-20 11:07:30,455] [INFO] [real_accelerator.py:222:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-12-20 11:07:43,260] [INFO] [comm.py:652:init_distributed] cdb=None
[2024-12-20 11:07:43,260] [INFO] [comm.py:683:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1793, in _get_module
[rank0]:     return importlib.import_module("." + module_name, self.__name__)
[rank0]:   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[rank0]:     return _bootstrap._gcd_import(name[level:], package, level)
[rank0]:   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[rank0]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[rank0]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[rank0]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[rank0]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[rank0]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 45, in <module>
[rank0]:     from ...modeling_flash_attention_utils import _flash_attention_forward
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/transformers/modeling_flash_attention_utils.py", line 30, in <module>
[rank0]:     from flash_attn.bert_padding import index_first_axis, pad_input, unpad_input  # noqa
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
[rank0]:     from flash_attn.flash_attn_interface import (
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 15, in <module>
[rank0]:     import flash_attn_2_cuda as flash_attn_gpu
[rank0]: ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

[rank0]: The above exception was the direct cause of the following exception:

[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/diffusion-pipe/train.py", line 214, in <module>
[rank0]:     from models import hunyuan_video
[rank0]:   File "/workspace/diffusion-pipe/models/hunyuan_video.py", line 22, in <module>
[rank0]:     from hyvideo.text_encoder import TextEncoder
[rank0]:   File "/workspace/diffusion-pipe/submodules/HunyuanVideo/hyvideo/text_encoder/__init__.py", line 7, in <module>
[rank0]:     from transformers import CLIPTextModel, CLIPTokenizer, AutoTokenizer, AutoModel
[rank0]:   File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1782, in __getattr__
[rank0]:     value = getattr(module, name)
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1781, in __getattr__
[rank0]:     module = self._get_module(self._class_to_module[name])
[rank0]:   File "/workspace/diffusion-pipe/venv/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1795, in _get_module
[rank0]:     raise RuntimeError(
[rank0]: RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
[rank0]: libcudart.so.11.0: cannot open shared object file: No such file or directory
[2024-12-20 11:07:44,643] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 7500
[2024-12-20 11:07:44,643] [ERROR] [launch.py:325:sigkill_handler] ['/workspace/diffusion-pipe/venv/bin/python3', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml'] exits with return code = 1
```

**Comment by tdrussell** [comment]
Something looks to be messed up with your environment, or with the flash attention installation. It seems a bit odd that it's looking for CUDA version 11 instead of 12. When I install torch==2.4.1 in a fresh env, it gets CUDA 12 by default.

Pytorch installation should put CUDA shared libraries in the env automatically. You can look for them, e.g. ```find /home/anon/miniconda3/envs/ -name "libcudart*"```

Also I always use conda for environments. Plain venv should work but conda makes it easy to install things like nvcc which deepspeed needs as well as some other things.

**Comment by popovidis** [comment]
> Something looks to be messed up with your environment, or with the flash attention installation. It seems a bit odd that it's looking for CUDA version 11 instead of 12. When I install torch==2.4.1 in a fresh env, it gets CUDA 12 by default.
> 
> Pytorch installation should put CUDA shared libraries in the env automatically. You can look for them, e.g. `find /home/anon/miniconda3/envs/ -name "libcudart*"`
> 
> Also I always use conda for environments. Plain venv should work but conda makes it easy to install things like nvcc which deepspeed needs as well as some other things.

I was using venv on runpod, they have torch come with it. I will try conda.

**Comment by popovidis** [comment]
conda > venv
