### ISSUE TITLE
offload type

### ISSUE THREAD

**Issue by Bocchi-Chan2023** [tdrussell/diffusion-pipe#8]
is 'offload' type working?
I have already installed requirements.txt and torchao 0.7.0.
When I tried this with hunyuan, the following error occurred:

[2024-12-14 00:48:42,662] [INFO] [config.py:1003:print]   zero_config .................. stage=0 contiguous_gradients=True reduce_scatter=True reduce_bucket_size=500000000 use_multi_rank_bucket_allreduce=True allgather_partitions=True allgather_bucket_size=500000000 overlap_comm=False load_from_fp32_weights=True elastic_checkpoint=False offload_param=None offload_optimizer=None sub_group_size=1000000000 cpu_offload_param=None cpu_offload_use_pin_memory=None cpu_offload=None prefetch_bucket_size=50000000 param_persistence_threshold=100000 model_persistence_threshold=9223372036854775807 max_live_parameters=1000000000 max_reuse_distance=1000000000 gather_16bit_weights_on_model_save=False module_granularity_threshold=0 use_all_reduce_for_fetch_params=False stage3_gather_fp16_weights_on_model_save=False ignore_unused_parameters=True legacy_stage1=False round_robin_gradients=False zero_hpz_partition_size=1 zero_quantized_weights=False zero_quantized_nontrainable_weights=False zero_quantized_gradients=False mics_shard_size=-1 mics_hierarchical_params_gather=False memory_efficient_linear=True pipeline_loading_checkpoint=False override_module_apply=True
[2024-12-14 00:48:42,662] [INFO] [config.py:1003:print]   zero_enabled ................. False
[2024-12-14 00:48:42,662] [INFO] [config.py:1003:print]   zero_force_ds_cpu_optimizer .. True
[2024-12-14 00:48:42,663] [INFO] [config.py:1003:print]   zero_optimization_stage ...... 0
[2024-12-14 00:48:42,663] [INFO] [config.py:989:print_user_config]   json = {
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 4,
    "gradient_clipping": 1.0,
    "steps_per_print": 1
}
[2024-12-14 00:48:42,663] [INFO] [engine.py:105:__init__] CONFIG: micro_batches=4 micro_batch_size=1
[2024-12-14 00:48:42,663] [INFO] [engine.py:146:__init__] is_pipe_partitioned= False is_grad_partitioned= False
[2024-12-14 00:48:42,879] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=63 [0, 63) STAGE_PARAMS=161218560 (161.219M) TOTAL_PARAMS=161218560 (161.219M) UNIQUE_PARAMS=161218560 (161.219M)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/moon/diffusion-pipe/train.py", line 387, in <module>
[rank0]:     lr_scheduler = torch.optim.lr_scheduler.ConstantLR(optimizer, factor=1.0)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/moon/.local/lib/python3.12/site-packages/torch/optim/lr_scheduler.py", line 663, in __init__
[rank0]:     super().__init__(optimizer, last_epoch, verbose)
[rank0]:   File "/home/moon/.local/lib/python3.12/site-packages/torch/optim/lr_scheduler.py", line 99, in __init__
[rank0]:     raise TypeError(f"{type(optimizer).__name__} is not an Optimizer")
[rank0]: TypeError: CPUOffloadOptimizer is not an Optimizer
[rank0]:[W1214 00:48:43.144969766 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
[2024-12-14 00:48:47,945] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 5751
[2024-12-14 00:48:48,013] [ERROR] [launch.py:325:sigkill_handler] ['/home/moon/miniconda3/envs/diffusion-pipe/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/hunyuan_video.toml'] exits with return code = 1

**Comment by Bocchi-Chan2023** [comment]
nvm it can be fixed
https://github.com/pytorch/ao/issues/1209

**Comment by tdrussell** [comment]
I don't think I ever did a training run with CPUOffloadOptimizer. It was from early experiments where I was finding various ways to full finetune Flux with 4x4090. IIRC, even my 128GB RAM wasn't enough for CPUOffloadOptimizer for flux.

**Comment by Bocchi-Chan2023** [comment]
> I don't think I ever did a training run with CPUOffloadOptimizer. It was from early experiments where I was finding various ways to full finetune Flux with 4x4090. IIRC, even my 128GB RAM wasn't enough for CPUOffloadOptimizer for flux.

Thank you very much. I tried that, but the RAM was too slow and I gave up on training hunyuan
